package com.carlink.navigation

import androidx.annotation.DrawableRes
import com.carlink.R

/**
 * Maps CPManeuverType (0-53) to VectorDrawable resource IDs for cluster display.
 *
 * Roundabout exit types (28-46) intentionally fall back to cp_maneuver_06_enter_roundabout.
 *
 * History: Phase A (D15, 2026-05-26) attempted to ship per-exit drawables (RoundaboutExit1..19)
 * keyed by the now-correctly-forwarded NaviManeuverType integer. Live-tested on Carmel, IN
 * routes and visually wrong: the static library encodes a single fixed spoke layout (4 spokes
 * at 90° increments, generated by compute_angle_turns.py), so "exit 3" on a 5-spoke Carmel
 * roundabout pointed at the wrong physical angle. The CPManeuverType integer is fundamentally
 * lossy — it carries the exit ordinal but discards the actual spoke geometry that varies
 * per junction. The 19 cp_maneuver_NN_roundabout_exit_M.xml files are kept in res/drawable
 * for reference but the picker no longer routes to them — they would lie about geometry.
 *
 * The correct fix is Phase C (task D16): JunctionComposer reads the 0x5202 burst's
 * field 0x000a (multi-occurrence spoke angle list) + field 0x000b (exit angle) at
 * route-calculation time and pre-composes a Bitmap per maneuver matching Apple's MapKit
 * bezier-builder output for that specific junction. Per-step events look up the
 * pre-composed icon by (NaviManeuverType, NaviRoadName) — zero compose latency on the
 * hot path. When D16 lands, this resolver will be bypassed for any maneuver where the
 * composer succeeded, with this file remaining only as the fallback for unknown types.
 *
 * Keep in sync with [ManeuverMapper.mapManeuverType]: both paths read the same cpType and
 * both feed the same Maneuver object in ManeuverMapper.buildManeuverForType. If one learns
 * a new code (e.g., protocol extension beyond 53) without the other, the cluster will
 * render an icon that contradicts the Car-App-Library-driven Maneuver.TYPE_* semantic.
 */
object ManeuverIconRenderer {
    /** 1:1 mapping: array index == CPManeuverType value. */
    private val CP_DRAWABLES =
        intArrayOf(
            R.drawable.cp_maneuver_00_no_turn, // 0
            R.drawable.cp_maneuver_01_left_turn, // 1
            R.drawable.cp_maneuver_02_right_turn, // 2
            R.drawable.cp_maneuver_03_straight_ahead, // 3
            R.drawable.cp_maneuver_04_uturn, // 4
            R.drawable.cp_maneuver_05_follow_road, // 5
            R.drawable.cp_maneuver_06_enter_roundabout, // 6
            R.drawable.cp_maneuver_07_exit_roundabout, // 7
            R.drawable.cp_maneuver_08_off_ramp, // 8
            R.drawable.cp_maneuver_09_on_ramp, // 9
            R.drawable.cp_maneuver_10_arrive_end_of_navigation, // 10
            R.drawable.cp_maneuver_11_start_route, // 11
            R.drawable.cp_maneuver_12_arrive_at_destination, // 12
            R.drawable.cp_maneuver_13_keep_left, // 13
            R.drawable.cp_maneuver_14_keep_right, // 14
            R.drawable.cp_maneuver_15_enter_ferry, // 15
            R.drawable.cp_maneuver_16_exit_ferry, // 16
            R.drawable.cp_maneuver_17_change_ferry, // 17
            R.drawable.cp_maneuver_18_start_route_with_uturn, // 18
            R.drawable.cp_maneuver_19_uturn_at_roundabout, // 19
            R.drawable.cp_maneuver_20_left_turn_at_end, // 20
            R.drawable.cp_maneuver_21_right_turn_at_end, // 21
            R.drawable.cp_maneuver_22_highway_off_ramp_left, // 22
            R.drawable.cp_maneuver_23_highway_off_ramp_right, // 23
            R.drawable.cp_maneuver_24_arrive_at_destination_left, // 24
            R.drawable.cp_maneuver_25_arrive_at_destination_right, // 25
            R.drawable.cp_maneuver_26_uturn_when_possible, // 26
            R.drawable.cp_maneuver_27_arrive_end_of_directions, // 27
            // 28-46: Roundabout exits — pick the Apple-extracted AVD whose embedded arrow
            // angle matches Apple's CARD-ICON convention (Exit1=right, Exit2=straight,
            // Exit3=left, Exit4=back). The lib's file name "_exit_N" reflects its extraction
            // index (endAngle = -π/2 + N·π/4 = 8 cardinals at 45° spacing), NOT the CP
            // exit ordinal. So cpType 28 (Exit1=right) maps to LIB N=2 (east arrow), etc.
            //   cpType N % 4: 1→right→lib N=2, 2→straight→lib N=8, 3→left→lib N=6, 0→back→lib N=4
            R.drawable.cp_maneuver_29_roundabout_exit_2, // 28 Exit1  = right  (lib N=2 / east)
            R.drawable.cp_maneuver_35_roundabout_exit_8, // 29 Exit2  = straight (lib N=8 / north)
            R.drawable.cp_maneuver_33_roundabout_exit_6, // 30 Exit3  = left   (lib N=6 / west)
            R.drawable.cp_maneuver_31_roundabout_exit_4, // 31 Exit4  = U-turn back (lib N=4 / south)
            R.drawable.cp_maneuver_29_roundabout_exit_2, // 32 Exit5  ≈ right  (cycle)
            R.drawable.cp_maneuver_35_roundabout_exit_8, // 33 Exit6  ≈ straight
            R.drawable.cp_maneuver_33_roundabout_exit_6, // 34 Exit7  ≈ left
            R.drawable.cp_maneuver_31_roundabout_exit_4, // 35 Exit8  ≈ back
            R.drawable.cp_maneuver_29_roundabout_exit_2, // 36 Exit9  ≈ right
            R.drawable.cp_maneuver_35_roundabout_exit_8, // 37 Exit10 ≈ straight
            R.drawable.cp_maneuver_33_roundabout_exit_6, // 38 Exit11 ≈ left
            R.drawable.cp_maneuver_31_roundabout_exit_4, // 39 Exit12 ≈ back
            R.drawable.cp_maneuver_29_roundabout_exit_2, // 40 Exit13 ≈ right
            R.drawable.cp_maneuver_35_roundabout_exit_8, // 41 Exit14 ≈ straight
            R.drawable.cp_maneuver_33_roundabout_exit_6, // 42 Exit15 ≈ left
            R.drawable.cp_maneuver_31_roundabout_exit_4, // 43 Exit16 ≈ back
            R.drawable.cp_maneuver_29_roundabout_exit_2, // 44 Exit17 ≈ right
            R.drawable.cp_maneuver_35_roundabout_exit_8, // 45 Exit18 ≈ straight
            R.drawable.cp_maneuver_33_roundabout_exit_6, // 46 Exit19 ≈ left
            R.drawable.cp_maneuver_47_sharp_left_turn, // 47
            R.drawable.cp_maneuver_48_sharp_right_turn, // 48
            R.drawable.cp_maneuver_49_slight_left_turn, // 49
            R.drawable.cp_maneuver_50_slight_right_turn, // 50
            R.drawable.cp_maneuver_51_change_highway, // 51
            R.drawable.cp_maneuver_52_change_highway_left, // 52
            R.drawable.cp_maneuver_53_change_highway_right, // 53
        )

    @DrawableRes
    fun drawableForManeuver(cpType: Int): Int {
        // Fallback for negative / >53 / future-protocol cpType: renders the
        // straight-ahead arrow (cp_maneuver_00_no_turn). This can visually contradict
        // a real turn; consider emitting a PROTO_UNKNOWN log if unknown codes need
        // forensic tracking. No dedicated "unknown maneuver" drawable exists today.
        return CP_DRAWABLES.getOrElse(cpType) { CP_DRAWABLES[0] }
    }
}
